name: Enable Auto Merge
on:
  pull_request_target:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          enable: ${{ github.actor == 'kenhowardpdx' || github.actor == 'dependabot[bot]' }}
          merge_method: SQUASH
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
