name: Enable Auto Merge
on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          enable: ${{ github.actor == 'kenhowardpdx' }}
          token: ${{ secrets.GITHUB_TOKEN }}
