name: Enable Auto Merge
on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          enable: ${{ github.actor == 'kenhowardpdx' || github.actor == 'dependabot' }}
          merge_method: SQUASH
          token: ${{ secrets.AUTO_MERGE_TOKEN }}
